#!/bin/sh
# dwm-debug
# script to debug dwm in xephyr
# license: gplv3

# xephyr is not installed
install_xephyr() {
		echo "Xephyr not installed, please install it."
		exit 1
}

command -v Xephyr > /dev/null || install_xephyr

Xephyr -screen 1024x768 :80 &
sleep 1

export DISPLAY=:80
dwm
killall Xephyr

